version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: ecommerce_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flutter_user
      POSTGRES_PASSWORD: flutter_pass
      POSTGRES_DB: flutter_ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
